<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Plugmatic.Core\Plugmatic.Core.csproj" />
    <ProjectReference Include="..\..\src\Plugmatic.Location\Plugmatic.Location.csproj" />
    <ProjectReference Include="..\..\src\Plugmatic.Providers\Plugmatic.Providers.csproj" />
    <ProjectReference Include="..\..\src\Plugmatic.Radios\Plugmatic.Radios.csproj" />
    <ProjectReference Include="..\..\src\Plugmatic.Radios.Dm32uv\Plugmatic.Radios.Dm32uv.csproj" />
    <ProjectReference Include="..\..\src\Plugmatic.Cli\Plugmatic.Cli.csproj" />
    <ProjectReference Include="..\..\src\Plugmatic.Radios.D878uv\Plugmatic.Radios.D878uv.csproj" />
  </ItemGroup>

</Project>